# conda env create -f environment-cpu.yml
name: lcc
channels:
    - conda-forge
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - pillow
    - pip
    - pip:
        - tensorflow==1.9
        - keras
    - pyyaml
    - scikit-learn
    - scipy

